# Generated by Django 3.0.2 on 2020-01-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShopNumber', models.CharField(max_length=12)),
                ('CustomerNumber', models.CharField(max_length=12)),
                ('Amount', models.FloatField()),
            ],
        ),
    ]
